-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               10.6.7-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win64
-- HeidiSQL Version:             11.3.0.6295
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dumping database structure for migrazioni
CREATE DATABASE IF NOT EXISTS `migrazioni` /*!40100 DEFAULT CHARACTER SET utf8mb3 COLLATE utf8mb3_bin */;
USE `migrazioni`;

-- Dumping structure for table migrazioni.country_borders
CREATE TABLE IF NOT EXISTS `country_borders` (
  `country_code` varchar(2) COLLATE utf8mb3_bin NOT NULL,
  `country_name` varchar(100) COLLATE utf8mb3_bin DEFAULT NULL,
  `country_border_code` varchar(2) COLLATE utf8mb3_bin NOT NULL,
  `country_border_name` varchar(100) COLLATE utf8mb3_bin DEFAULT NULL,
  PRIMARY KEY (`country_code`,`country_border_code`),
  KEY `idx_country_code` (`country_code`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

-- Dumping data for table migrazioni.country_borders: 717 rows
/*!40000 ALTER TABLE `country_borders` DISABLE KEYS */;
INSERT INTO `country_borders` (`country_code`, `country_name`, `country_border_code`, `country_border_name`) VALUES
	('AI', 'Anguilla', '', ''),
	('AL', 'Albania', 'GR', 'Greece'),
	('AL', 'Albania', 'ME', 'Montenegro'),
	('AL', 'Albania', 'MK', 'North Macedonia'),
	('AL', 'Albania', 'RS', 'Serbia'),
	('AM', 'Armenia', 'AZ', 'Azerbaijan'),
	('AM', 'Armenia', 'GE', 'Georgia'),
	('AM', 'Armenia', 'IR', 'Iran (Islamic Republic of)'),
	('AM', 'Armenia', 'TR', 'Turkey'),
	('AO', 'Angola', 'CG', 'Congo'),
	('AO', 'Angola', 'CD', 'Congo (the Democratic Republic of the)'),
	('AO', 'Angola', 'NA', 'Namibia'),
	('AO', 'Angola', 'ZM', 'Zambia'),
	('AQ', 'Antarctica', '', ''),
	('AR', 'Argentina', 'BO', 'Bolivia (Plurinational State Of)'),
	('AR', 'Argentina', 'BR', 'Brazil'),
	('AR', 'Argentina', 'CL', 'Chile'),
	('AR', 'Argentina', 'PY', 'Paraguay'),
	('AR', 'Argentina', 'UY', 'Uruguay'),
	('AS', 'American Samoa', '', ''),
	('AT', 'Austria', 'CZ', 'Czechia'),
	('AT', 'Austria', 'DE', 'Germany'),
	('AT', 'Austria', 'HU', 'Hungary'),
	('AT', 'Austria', 'IT', 'Italy'),
	('AT', 'Austria', 'LI', 'Liechtenstein'),
	('AT', 'Austria', 'SK', 'Slovakia'),
	('AT', 'Austria', 'SI', 'Slovenia'),
	('AT', 'Austria', 'CH', 'Switzerland'),
	('AU', 'Australia', '', ''),
	('AW', 'Aruba', '', ''),
	('AX', 'Aland Islands', '', ''),
	('AZ', 'Azerbaijan', 'AM', 'Armenia'),
	('AZ', 'Azerbaijan', 'GE', 'Georgia'),
	('AZ', 'Azerbaijan', 'IR', 'Iran (Islamic Republic of)'),
	('AZ', 'Azerbaijan', 'RU', 'Russian Federation'),
	('AZ', 'Azerbaijan', 'TR', 'Turkey'),
	('BA', 'Bosnia and Herzegovina', 'HR', 'Croatia'),
	('BA', 'Bosnia and Herzegovina', 'ME', 'Montenegro'),
	('BA', 'Bosnia and Herzegovina', 'RS', 'Serbia'),
	('BB', 'Barbados', '', ''),
	('BD', 'Bangladesh', 'IN', 'India'),
	('BD', 'Bangladesh', 'MM', 'Myanmar'),
	('BE', 'Belgium', 'FR', 'France'),
	('BE', 'Belgium', 'DE', 'Germany'),
	('BE', 'Belgium', 'LU', 'Luxembourg'),
	('BE', 'Belgium', 'NL', 'Netherlands'),
	('BF', 'Burkina Faso', 'BJ', 'Benin'),
	('BF', 'Burkina Faso', 'CI', 'Cote d’Ivoire'),
	('BF', 'Burkina Faso', 'GH', 'Ghana'),
	('BF', 'Burkina Faso', 'ML', 'Mali'),
	('BF', 'Burkina Faso', 'NE', 'Niger'),
	('BF', 'Burkina Faso', 'TG', 'Togo'),
	('BG', 'Bulgaria', 'GR', 'Greece'),
	('BG', 'Bulgaria', 'MK', 'North Macedonia'),
	('BG', 'Bulgaria', 'RO', 'Romania'),
	('BG', 'Bulgaria', 'RS', 'Serbia'),
	('BG', 'Bulgaria', 'TR', 'Turkey'),
	('BH', 'Bahrain', '', ''),
	('BI', 'Burundi', 'CD', 'Congo (the Democratic Republic of the)'),
	('BI', 'Burundi', 'RW', 'Rwanda'),
	('BI', 'Burundi', 'TZ', 'Tanzania (the United Republic of)'),
	('BJ', 'Benin', 'BF', 'Burkina Faso'),
	('BJ', 'Benin', 'NE', 'Niger'),
	('BJ', 'Benin', 'NG', 'Nigeria'),
	('BJ', 'Benin', 'TG', 'Togo'),
	('BL', 'Saint Barthelemy', '', ''),
	('BM', 'Bermuda', '', ''),
	('BN', 'Brunei Darussalam', 'MY', 'Malaysia'),
	('BO', 'Bolivia (Plurinational State Of)', 'AR', 'Argentina'),
	('BO', 'Bolivia (Plurinational State Of)', 'BR', 'Brazil'),
	('BO', 'Bolivia (Plurinational State Of)', 'CL', 'Chile'),
	('BO', 'Bolivia (Plurinational State Of)', 'PY', 'Paraguay'),
	('BO', 'Bolivia (Plurinational State Of)', 'PE', 'Peru'),
	('BQ', 'Bonaire, Sint Eustatius and Saba', '', ''),
	('BR', 'Brazil', 'AR', 'Argentina'),
	('BR', 'Brazil', 'BO', 'Bolivia (Plurinational State Of)'),
	('BR', 'Brazil', 'CO', 'Colombia'),
	('BR', 'Brazil', 'GF', 'French Guiana'),
	('BR', 'Brazil', 'GY', 'Guyana'),
	('BR', 'Brazil', 'PY', 'Paraguay'),
	('BR', 'Brazil', 'PE', 'Peru'),
	('BR', 'Brazil', 'SR', 'Suriname'),
	('BR', 'Brazil', 'UY', 'Uruguay'),
	('BR', 'Brazil', 'VE', 'Venezuela (Bolivarian Republic of)'),
	('BS', 'Bahamas', '', ''),
	('BT', 'Bhutan', 'CN', 'China'),
	('BT', 'Bhutan', 'IN', 'India'),
	('BV', 'Bouvet Island', '', ''),
	('BW', 'Botswana', 'NA', 'Namibia'),
	('BW', 'Botswana', 'ZA', 'South Africa'),
	('BW', 'Botswana', 'ZM', 'Zambia'),
	('BW', 'Botswana', 'ZW', 'Zimbabwe'),
	('BY', 'Belarus', 'LV', 'Latvia'),
	('BY', 'Belarus', 'LT', 'Lithuania'),
	('BY', 'Belarus', 'PL', 'Poland'),
	('BY', 'Belarus', 'RU', 'Russian Federation'),
	('BY', 'Belarus', 'UA', 'Ukraine'),
	('BZ', 'Belize', 'GT', 'Guatemala'),
	('BZ', 'Belize', 'MX', 'Mexico'),
	('CA', 'Canada', 'US', 'United States of America'),
	('CC', 'Cocos (Keeling) Islands', '', ''),
	('CD', 'Congo (the Democratic Republic of the)', 'AO', 'Angola'),
	('CD', 'Congo (the Democratic Republic of the)', 'BI', 'Burundi'),
	('CD', 'Congo (the Democratic Republic of the)', 'CF', 'Central African Republic'),
	('CD', 'Congo (the Democratic Republic of the)', 'CG', 'Congo'),
	('CD', 'Congo (the Democratic Republic of the)', 'RW', 'Rwanda'),
	('CD', 'Congo (the Democratic Republic of the)', 'SS', 'South Sudan'),
	('CD', 'Congo (the Democratic Republic of the)', 'TZ', 'Tanzania (the United Republic of)'),
	('CD', 'Congo (the Democratic Republic of the)', 'UG', 'Uganda'),
	('CD', 'Congo (the Democratic Republic of the)', 'ZM', 'Zambia'),
	('CF', 'Central African Republic', 'CM', 'Cameroon'),
	('CF', 'Central African Republic', 'TD', 'Chad'),
	('CF', 'Central African Republic', 'CG', 'Congo'),
	('CF', 'Central African Republic', 'CD', 'Congo (the Democratic Republic of the)'),
	('CF', 'Central African Republic', 'SS', 'South Sudan'),
	('CF', 'Central African Republic', 'SD', 'Sudan'),
	('CG', 'Congo', 'AO', 'Angola'),
	('CG', 'Congo', 'CM', 'Cameroon'),
	('CG', 'Congo', 'CF', 'Central African Republic'),
	('CG', 'Congo', 'CD', 'Congo (the Democratic Republic of the)'),
	('CG', 'Congo', 'GA', 'Gabon'),
	('CH', 'Switzerland', 'AT', 'Austria'),
	('CH', 'Switzerland', 'FR', 'France'),
	('CH', 'Switzerland', 'DE', 'Germany'),
	('CH', 'Switzerland', 'IT', 'Italy'),
	('CH', 'Switzerland', 'LI', 'Liechtenstein'),
	('CI', 'Cote d’Ivoire', 'BF', 'Burkina Faso'),
	('CI', 'Cote d’Ivoire', 'GH', 'Ghana'),
	('CI', 'Cote d’Ivoire', 'GN', 'Guinea'),
	('CI', 'Cote d’Ivoire', 'LR', 'Liberia'),
	('CI', 'Cote d’Ivoire', 'ML', 'Mali'),
	('CK', 'Cook Islands', '', ''),
	('CL', 'Chile', 'AR', 'Argentina'),
	('CL', 'Chile', 'BO', 'Bolivia (Plurinational State Of)'),
	('CL', 'Chile', 'PE', 'Peru'),
	('CM', 'Cameroon', 'CF', 'Central African Republic'),
	('CM', 'Cameroon', 'TD', 'Chad'),
	('CM', 'Cameroon', 'CG', 'Congo'),
	('CM', 'Cameroon', 'GQ', 'Equatorial Guinea'),
	('CM', 'Cameroon', 'GA', 'Gabon'),
	('CM', 'Cameroon', 'NG', 'Nigeria'),
	('CN', 'China', 'AF', 'Afghanistan'),
	('CN', 'China', 'BT', 'Bhutan'),
	('CN', 'China', 'HK', 'Hong Kong'),
	('CN', 'China', 'IN', 'India'),
	('CN', 'China', 'KZ', 'Kazakhstan'),
	('CN', 'China', 'KP', 'Korea (Democratic People\'s Republic of)'),
	('CN', 'China', 'KG', 'Kyrgyzstan'),
	('CN', 'China', 'LA', 'Lao People\'s Democratic Republic'),
	('CN', 'China', 'MO', 'Macao'),
	('CN', 'China', 'MN', 'Mongolia'),
	('CN', 'China', 'MM', 'Myanmar'),
	('CN', 'China', 'NP', 'Nepal'),
	('CN', 'China', 'PK', 'Pakistan'),
	('CN', 'China', 'RU', 'Russian Federation'),
	('CN', 'China', 'TJ', 'Tajikistan'),
	('CN', 'China', 'VN', 'Viet Nam'),
	('CO', 'Colombia', 'BR', 'Brazil'),
	('CO', 'Colombia', 'EC', 'Ecuador'),
	('CO', 'Colombia', 'PA', 'Panama'),
	('CO', 'Colombia', 'PE', 'Peru'),
	('CO', 'Colombia', 'VE', 'Venezuela (Bolivarian Republic of)'),
	('CR', 'Costa Rica', 'NI', 'Nicaragua'),
	('CR', 'Costa Rica', 'PA', 'Panama'),
	('CU', 'Cuba', '', ''),
	('CV', 'Cabo Verde', '', ''),
	('CW', 'Curacao', '', ''),
	('CX', 'Christmas Island', '', ''),
	('CY', 'Cyprus', '', ''),
	('CZ', 'Czechia', 'AT', 'Austria'),
	('CZ', 'Czechia', 'DE', 'Germany'),
	('CZ', 'Czechia', 'PL', 'Poland'),
	('CZ', 'Czechia', 'SK', 'Slovakia'),
	('DE', 'Germany', 'AT', 'Austria'),
	('DE', 'Germany', 'BE', 'Belgium'),
	('DE', 'Germany', 'CZ', 'Czechia'),
	('DE', 'Germany', 'DK', 'Denmark'),
	('DE', 'Germany', 'FR', 'France'),
	('DE', 'Germany', 'LU', 'Luxembourg'),
	('DE', 'Germany', 'NL', 'Netherlands'),
	('DE', 'Germany', 'PL', 'Poland'),
	('DE', 'Germany', 'CH', 'Switzerland'),
	('DJ', 'Djibouti', 'ER', 'Eritrea'),
	('DJ', 'Djibouti', 'ET', 'Ethiopia'),
	('DJ', 'Djibouti', 'SO', 'Somalia'),
	('DK', 'Denmark', 'DE', 'Germany'),
	('DM', 'Dominica', '', ''),
	('DO', 'Dominican Republic', 'HT', 'Haiti'),
	('DZ', 'Algeria', 'LY', 'Libya'),
	('DZ', 'Algeria', 'ML', 'Mali'),
	('DZ', 'Algeria', 'MR', 'Mauritania'),
	('DZ', 'Algeria', 'MA', 'Morocco'),
	('DZ', 'Algeria', 'NE', 'Niger'),
	('DZ', 'Algeria', 'TN', 'Tunisia'),
	('DZ', 'Algeria', 'EH', 'Western Sahara'),
	('EC', 'Ecuador', 'CO', 'Colombia'),
	('EC', 'Ecuador', 'PE', 'Peru'),
	('EE', 'Estonia', 'LV', 'Latvia'),
	('EE', 'Estonia', 'RU', 'Russian Federation'),
	('EG', 'Egypt', 'IL', 'Israel'),
	('EG', 'Egypt', 'LY', 'Libya'),
	('EG', 'Egypt', 'PS', 'Palestine, State of'),
	('EG', 'Egypt', 'SD', 'Sudan'),
	('EH', 'Western Sahara', 'DZ', 'Algeria'),
	('EH', 'Western Sahara', 'MR', 'Mauritania'),
	('EH', 'Western Sahara', 'MA', 'Morocco'),
	('ER', 'Eritrea', 'DJ', 'Djibouti'),
	('ER', 'Eritrea', 'ET', 'Ethiopia'),
	('ER', 'Eritrea', 'SD', 'Sudan'),
	('ES', 'Spain', 'AD', 'Andorra'),
	('ES', 'Spain', 'FR', 'France'),
	('ES', 'Spain', 'GI', 'Gibraltar'),
	('ES', 'Spain', 'MA', 'Morocco'),
	('ES', 'Spain', 'PT', 'Portugal'),
	('ET', 'Ethiopia', 'DJ', 'Djibouti'),
	('ET', 'Ethiopia', 'ER', 'Eritrea'),
	('ET', 'Ethiopia', 'KE', 'Kenya'),
	('ET', 'Ethiopia', 'SO', 'Somalia'),
	('ET', 'Ethiopia', 'SS', 'South Sudan'),
	('ET', 'Ethiopia', 'SD', 'Sudan'),
	('FI', 'Finland', 'NO', 'Norway'),
	('FI', 'Finland', 'RU', 'Russian Federation'),
	('FI', 'Finland', 'SE', 'Sweden'),
	('FJ', 'Fiji', '', ''),
	('FK', 'Falkland Islands (Malvinas)', '', ''),
	('FM', 'Micronesia (Federated States of)', '', ''),
	('FO', 'Faroe Islands', '', ''),
	('FR', 'France', 'AD', 'Andorra'),
	('FR', 'France', 'BE', 'Belgium'),
	('FR', 'France', 'DE', 'Germany'),
	('FR', 'France', 'IT', 'Italy'),
	('FR', 'France', 'LU', 'Luxembourg'),
	('FR', 'France', 'MC', 'Monaco'),
	('FR', 'France', 'ES', 'Spain'),
	('FR', 'France', 'CH', 'Switzerland'),
	('GA', 'Gabon', 'CM', 'Cameroon'),
	('GA', 'Gabon', 'CG', 'Congo'),
	('GA', 'Gabon', 'GQ', 'Equatorial Guinea'),
	('GB', 'United Kingdom of Great Britain and Northern Ireland', 'IE', 'Ireland'),
	('GD', 'Grenada', '', ''),
	('GE', 'Georgia', 'AM', 'Armenia'),
	('GE', 'Georgia', 'AZ', 'Azerbaijan'),
	('GE', 'Georgia', 'RU', 'Russian Federation'),
	('GE', 'Georgia', 'TR', 'Turkey'),
	('GF', 'French Guiana', 'BR', 'Brazil'),
	('GF', 'French Guiana', 'SR', 'Suriname'),
	('GG', 'Guernsey', '', ''),
	('GH', 'Ghana', 'BF', 'Burkina Faso'),
	('GH', 'Ghana', 'CI', 'Cote d’Ivoire'),
	('GH', 'Ghana', 'TG', 'Togo'),
	('GI', 'Gibraltar', 'ES', 'Spain'),
	('GL', 'Greenland', '', ''),
	('GM', 'Gambia (the)', 'SN', 'Senegal'),
	('GN', 'Guinea', 'CI', 'Cote d’Ivoire'),
	('GN', 'Guinea', 'GW', 'Guinea-Bissau'),
	('GN', 'Guinea', 'LR', 'Liberia'),
	('GN', 'Guinea', 'ML', 'Mali'),
	('GN', 'Guinea', 'SN', 'Senegal'),
	('GN', 'Guinea', 'SL', 'Sierra Leone'),
	('GP', 'Guadeloupe', '', ''),
	('GQ', 'Equatorial Guinea', 'CM', 'Cameroon'),
	('GQ', 'Equatorial Guinea', 'GA', 'Gabon'),
	('GR', 'Greece', 'AL', 'Albania'),
	('GR', 'Greece', 'BG', 'Bulgaria'),
	('GR', 'Greece', 'MK', 'North Macedonia'),
	('GR', 'Greece', 'TR', 'Turkey'),
	('GS', 'South Georgia and the South Sandwich Islands', '', ''),
	('GT', 'Guatemala', 'BZ', 'Belize'),
	('GT', 'Guatemala', 'SV', 'El Salvador'),
	('GT', 'Guatemala', 'HN', 'Honduras'),
	('GT', 'Guatemala', 'MX', 'Mexico'),
	('GU', 'Guam', '', ''),
	('GW', 'Guinea-Bissau', 'GN', 'Guinea'),
	('GW', 'Guinea-Bissau', 'SN', 'Senegal'),
	('GY', 'Guyana', 'BR', 'Brazil'),
	('GY', 'Guyana', 'SR', 'Suriname'),
	('GY', 'Guyana', 'VE', 'Venezuela (Bolivarian Republic of)'),
	('HK', 'Hong Kong', 'CN', 'China'),
	('HM', 'Heard Island and McDonald Islands', '', ''),
	('HN', 'Honduras', 'SV', 'El Salvador'),
	('HN', 'Honduras', 'GT', 'Guatemala'),
	('HN', 'Honduras', 'NI', 'Nicaragua'),
	('HR', 'Croatia', 'BA', 'Bosnia and Herzegovina'),
	('HR', 'Croatia', 'HU', 'Hungary'),
	('HR', 'Croatia', 'ME', 'Montenegro'),
	('HR', 'Croatia', 'RS', 'Serbia'),
	('HR', 'Croatia', 'SI', 'Slovenia'),
	('HT', 'Haiti', 'DO', 'Dominican Republic'),
	('HU', 'Hungary', 'AT', 'Austria'),
	('HU', 'Hungary', 'HR', 'Croatia'),
	('HU', 'Hungary', 'RO', 'Romania'),
	('HU', 'Hungary', 'RS', 'Serbia'),
	('HU', 'Hungary', 'SK', 'Slovakia'),
	('HU', 'Hungary', 'SI', 'Slovenia'),
	('HU', 'Hungary', 'UA', 'Ukraine'),
	('ID', 'Indonesia', 'MY', 'Malaysia'),
	('ID', 'Indonesia', 'PG', 'Papua New Guinea'),
	('ID', 'Indonesia', 'TL', 'Timor-Leste'),
	('IE', 'Ireland', 'GB', 'United Kingdom of Great Britain and Northern Ireland'),
	('IL', 'Israel', 'EG', 'Egypt'),
	('IL', 'Israel', 'JO', 'Jordan'),
	('IL', 'Israel', 'LB', 'Lebanon'),
	('IL', 'Israel', 'PS', 'Palestine, State of'),
	('IL', 'Israel', 'SY', 'Syrian Arab Republic'),
	('IM', 'Isle of Man', '', ''),
	('IN', 'India', 'BD', 'Bangladesh'),
	('IN', 'India', 'BT', 'Bhutan'),
	('IN', 'India', 'CN', 'China'),
	('IN', 'India', 'MM', 'Myanmar'),
	('IN', 'India', 'NP', 'Nepal'),
	('IN', 'India', 'PK', 'Pakistan'),
	('IO', 'British Indian Ocean Territory', '', ''),
	('IQ', 'Iraq', 'IR', 'Iran (Islamic Republic of)'),
	('IQ', 'Iraq', 'JO', 'Jordan'),
	('IQ', 'Iraq', 'KW', 'Kuwait'),
	('IQ', 'Iraq', 'SA', 'Saudi Arabia'),
	('IQ', 'Iraq', 'SY', 'Syrian Arab Republic'),
	('IQ', 'Iraq', 'TR', 'Turkey'),
	('IR', 'Iran (Islamic Republic of)', 'AF', 'Afghanistan'),
	('IR', 'Iran (Islamic Republic of)', 'AM', 'Armenia'),
	('IR', 'Iran (Islamic Republic of)', 'AZ', 'Azerbaijan'),
	('IR', 'Iran (Islamic Republic of)', 'IQ', 'Iraq'),
	('IR', 'Iran (Islamic Republic of)', 'PK', 'Pakistan'),
	('IR', 'Iran (Islamic Republic of)', 'TR', 'Turkey'),
	('IR', 'Iran (Islamic Republic of)', 'TM', 'Turkmenistan'),
	('IS', 'Iceland', '', ''),
	('IT', 'Italy', 'AT', 'Austria'),
	('IT', 'Italy', 'FR', 'France'),
	('IT', 'Italy', 'SM', 'San Marino'),
	('IT', 'Italy', 'SI', 'Slovenia'),
	('IT', 'Italy', 'CH', 'Switzerland'),
	('IT', 'Italy', 'VA', 'Holy See'),
	('JE', 'Jersey', '', ''),
	('JM', 'Jamaica', '', ''),
	('JO', 'Jordan', 'IQ', 'Iraq'),
	('JO', 'Jordan', 'IL', 'Israel'),
	('JO', 'Jordan', 'PS', 'Palestine, State of'),
	('JO', 'Jordan', 'SA', 'Saudi Arabia'),
	('JO', 'Jordan', 'SY', 'Syrian Arab Republic'),
	('JP', 'Japan', '', ''),
	('KE', 'Kenya', 'ET', 'Ethiopia'),
	('KE', 'Kenya', 'SO', 'Somalia'),
	('KE', 'Kenya', 'SS', 'South Sudan'),
	('KE', 'Kenya', 'TZ', 'Tanzania (the United Republic of)'),
	('KE', 'Kenya', 'UG', 'Uganda'),
	('KG', 'Kyrgyzstan', 'CN', 'China'),
	('KG', 'Kyrgyzstan', 'KZ', 'Kazakhstan'),
	('KG', 'Kyrgyzstan', 'TJ', 'Tajikistan'),
	('KG', 'Kyrgyzstan', 'UZ', 'Uzbekistan'),
	('KH', 'Cambodia', 'LA', 'Lao People\'s Democratic Republic'),
	('KH', 'Cambodia', 'TH', 'Thailand'),
	('KH', 'Cambodia', 'VN', 'Viet Nam'),
	('KI', 'Kiribati', '', ''),
	('KM', 'Comoros', '', ''),
	('KN', 'Saint Kitts and Nevis', '', ''),
	('KP', 'Korea (Democratic People\'s Republic of)', 'CN', 'China'),
	('KP', 'Korea (Democratic People\'s Republic of)', 'KR', 'Korea (the Republic of)'),
	('KP', 'Korea (Democratic People\'s Republic of)', 'RU', 'Russian Federation'),
	('KR', 'Korea (the Republic of)', 'KP', 'Korea (Democratic People\'s Republic of)'),
	('KW', 'Kuwait', 'IQ', 'Iraq'),
	('KW', 'Kuwait', 'SA', 'Saudi Arabia'),
	('KY', 'Cayman Islands', '', ''),
	('KZ', 'Kazakhstan', 'CN', 'China'),
	('KZ', 'Kazakhstan', 'KG', 'Kyrgyzstan'),
	('KZ', 'Kazakhstan', 'RU', 'Russian Federation'),
	('KZ', 'Kazakhstan', 'TM', 'Turkmenistan'),
	('KZ', 'Kazakhstan', 'UZ', 'Uzbekistan'),
	('LA', 'Lao People\'s Democratic Republic', 'CN', 'China'),
	('LA', 'Lao People\'s Democratic Republic', 'KH', 'Cambodia'),
	('LA', 'Lao People\'s Democratic Republic', 'MM', 'Myanmar'),
	('LA', 'Lao People\'s Democratic Republic', 'TH', 'Thailand'),
	('LA', 'Lao People\'s Democratic Republic', 'VN', 'Viet Nam'),
	('LB', 'Lebanon', 'IL', 'Israel'),
	('LB', 'Lebanon', 'SY', 'Syrian Arab Republic'),
	('LC', 'Saint Lucia', '', ''),
	('LI', 'Liechtenstein', 'AT', 'Austria'),
	('LI', 'Liechtenstein', 'CH', 'Switzerland'),
	('LK', 'Sri Lanka', '', ''),
	('LR', 'Liberia', 'CI', 'Cote d’Ivoire'),
	('LR', 'Liberia', 'GN', 'Guinea'),
	('LR', 'Liberia', 'SL', 'Sierra Leone'),
	('LS', 'Lesotho', 'ZA', 'South Africa'),
	('LT', 'Lithuania', 'BY', 'Belarus'),
	('LT', 'Lithuania', 'LV', 'Latvia'),
	('LT', 'Lithuania', 'PL', 'Poland'),
	('LT', 'Lithuania', 'RU', 'Russian Federation'),
	('LU', 'Luxembourg', 'BE', 'Belgium'),
	('LU', 'Luxembourg', 'DE', 'Germany'),
	('LU', 'Luxembourg', 'FR', 'France'),
	('LV', 'Latvia', 'BY', 'Belarus'),
	('LV', 'Latvia', 'EE', 'Estonia'),
	('LV', 'Latvia', 'LT', 'Lithuania'),
	('LV', 'Latvia', 'RU', 'Russian Federation'),
	('LY', 'Libya', 'DZ', 'Algeria'),
	('LY', 'Libya', 'TD', 'Chad'),
	('LY', 'Libya', 'EG', 'Egypt'),
	('LY', 'Libya', 'NE', 'Niger'),
	('LY', 'Libya', 'SD', 'Sudan'),
	('LY', 'Libya', 'TN', 'Tunisia'),
	('MA', 'Morocco', 'DZ', 'Algeria'),
	('MA', 'Morocco', 'ES', 'Spain'),
	('MA', 'Morocco', 'EH', 'Western Sahara'),
	('MC', 'Monaco', 'FR', 'France'),
	('MD', 'Moldova (the Republic of)', 'RO', 'Romania'),
	('MD', 'Moldova (the Republic of)', 'UA', 'Ukraine'),
	('ME', 'Montenegro', 'AL', 'Albania'),
	('ME', 'Montenegro', 'BA', 'Bosnia and Herzegovina'),
	('ME', 'Montenegro', 'HR', 'Croatia'),
	('ME', 'Montenegro', 'RS', 'Serbia'),
	('MF', 'Saint Martin (French part)', 'SX', 'Sint Maarten (Dutch part)'),
	('MG', 'Madagascar', '', ''),
	('MH', 'Marshall Islands', '', ''),
	('MK', 'North Macedonia', 'AL', 'Albania'),
	('MK', 'North Macedonia', 'BG', 'Bulgaria'),
	('MK', 'North Macedonia', 'GR', 'Greece'),
	('MK', 'North Macedonia', 'RS', 'Serbia'),
	('ML', 'Mali', 'DZ', 'Algeria'),
	('ML', 'Mali', 'BF', 'Burkina Faso'),
	('ML', 'Mali', 'CI', 'Cote d’Ivoire'),
	('ML', 'Mali', 'GN', 'Guinea'),
	('ML', 'Mali', 'MR', 'Mauritania'),
	('ML', 'Mali', 'NE', 'Niger'),
	('ML', 'Mali', 'SN', 'Senegal'),
	('MM', 'Myanmar', 'BD', 'Bangladesh'),
	('MM', 'Myanmar', 'CN', 'China'),
	('MM', 'Myanmar', 'IN', 'India'),
	('MM', 'Myanmar', 'LA', 'Lao People\'s Democratic Republic'),
	('MM', 'Myanmar', 'TH', 'Thailand'),
	('MN', 'Mongolia', 'CN', 'China'),
	('MN', 'Mongolia', 'RU', 'Russian Federation'),
	('MO', 'Macao', 'CN', 'China'),
	('MP', 'Northern Mariana Islands', '', ''),
	('MQ', 'Martinique', '', ''),
	('MR', 'Mauritania', 'DZ', 'Algeria'),
	('MR', 'Mauritania', 'ML', 'Mali'),
	('MR', 'Mauritania', 'SN', 'Senegal'),
	('MR', 'Mauritania', 'EH', 'Western Sahara'),
	('MS', 'Montserrat', '', ''),
	('MT', 'Malta', '', ''),
	('MU', 'Mauritius', '', ''),
	('MV', 'Maldives', '', ''),
	('MW', 'Malawi', 'MZ', 'Mozambique'),
	('MW', 'Malawi', 'TZ', 'Tanzania (the United Republic of)'),
	('MW', 'Malawi', 'ZM', 'Zambia'),
	('MX', 'Mexico', 'BZ', 'Belize'),
	('MX', 'Mexico', 'GT', 'Guatemala'),
	('MX', 'Mexico', 'US', 'United States of America'),
	('MY', 'Malaysia', 'BN', 'Brunei Darussalam'),
	('MY', 'Malaysia', 'ID', 'Indonesia'),
	('MY', 'Malaysia', 'TH', 'Thailand'),
	('MZ', 'Mozambique', 'MW', 'Malawi'),
	('MZ', 'Mozambique', 'SZ', 'Eswatini'),
	('MZ', 'Mozambique', 'ZA', 'South Africa'),
	('MZ', 'Mozambique', 'TZ', 'Tanzania (the United Republic of)'),
	('MZ', 'Mozambique', 'ZM', 'Zambia'),
	('MZ', 'Mozambique', 'ZW', 'Zimbabwe'),
	('NA', 'Namibia', 'AO', 'Angola'),
	('NA', 'Namibia', 'BW', 'Botswana'),
	('NA', 'Namibia', 'ZA', 'South Africa'),
	('NA', 'Namibia', 'ZM', 'Zambia'),
	('NC', 'New Caledonia', '', ''),
	('NE', 'Niger', 'DZ', 'Algeria'),
	('NE', 'Niger', 'BJ', 'Benin'),
	('NE', 'Niger', 'BF', 'Burkina Faso'),
	('NE', 'Niger', 'TD', 'Chad'),
	('NE', 'Niger', 'LY', 'Libya'),
	('NE', 'Niger', 'ML', 'Mali'),
	('NE', 'Niger', 'NG', 'Nigeria'),
	('NF', 'Norfolk Island', '', ''),
	('NG', 'Nigeria', 'BJ', 'Benin'),
	('NG', 'Nigeria', 'CM', 'Cameroon'),
	('NG', 'Nigeria', 'TD', 'Chad'),
	('NG', 'Nigeria', 'NE', 'Niger'),
	('NI', 'Nicaragua', 'CR', 'Costa Rica'),
	('NI', 'Nicaragua', 'HN', 'Honduras'),
	('NL', 'Netherlands', 'BE', 'Belgium'),
	('NL', 'Netherlands', 'DE', 'Germany'),
	('NO', 'Norway', 'FI', 'Finland'),
	('NO', 'Norway', 'RU', 'Russian Federation'),
	('NO', 'Norway', 'SE', 'Sweden'),
	('NP', 'Nepal', 'CN', 'China'),
	('NP', 'Nepal', 'IN', 'India'),
	('NR', 'Nauru', '', ''),
	('NU', 'Niue', '', ''),
	('NZ', 'New Zealand', '', ''),
	('OM', 'Oman', 'AE', 'United Arab Emirates'),
	('OM', 'Oman', 'SA', 'Saudi Arabia'),
	('OM', 'Oman', 'YE', 'Yemen'),
	('PA', 'Panama', 'CO', 'Colombia'),
	('PA', 'Panama', 'CR', 'Costa Rica'),
	('PE', 'Peru', 'BO', 'Bolivia (Plurinational State Of)'),
	('PE', 'Peru', 'BR', 'Brazil'),
	('PE', 'Peru', 'CL', 'Chile'),
	('PE', 'Peru', 'CO', 'Colombia'),
	('PE', 'Peru', 'EC', 'Ecuador'),
	('PF', 'French Polynesia', '', ''),
	('PG', 'Papua New Guinea', 'ID', 'Indonesia'),
	('PH', 'Philippines', '', ''),
	('PK', 'Pakistan', 'AF', 'Afghanistan'),
	('PK', 'Pakistan', 'CN', 'China'),
	('PK', 'Pakistan', 'IN', 'India'),
	('PK', 'Pakistan', 'IR', 'Iran (Islamic Republic of)'),
	('PL', 'Poland', 'BY', 'Belarus'),
	('PL', 'Poland', 'CZ', 'Czechia'),
	('PL', 'Poland', 'DE', 'Germany'),
	('PL', 'Poland', 'LT', 'Lithuania'),
	('PL', 'Poland', 'RU', 'Russian Federation'),
	('PL', 'Poland', 'SK', 'Slovakia'),
	('PL', 'Poland', 'UA', 'Ukraine'),
	('PM', 'Saint Pierre and Miquelon', '', ''),
	('PN', 'Pitcairn', '', ''),
	('PR', 'Puerto Rico', '', ''),
	('PS', 'Palestine, State of', 'EG', 'Egypt'),
	('PS', 'Palestine, State of', 'IL', 'Israel'),
	('PS', 'Palestine, State of', 'JO', 'Jordan'),
	('PT', 'Portugal', 'ES', 'Spain'),
	('PW', 'Palau', '', ''),
	('PY', 'Paraguay', 'AR', 'Argentina'),
	('PY', 'Paraguay', 'BO', 'Bolivia (Plurinational State Of)'),
	('PY', 'Paraguay', 'BR', 'Brazil'),
	('QA', 'Qatar', 'SA', 'Saudi Arabia'),
	('RE', 'Reunion', '', ''),
	('RO', 'Romania', 'BG', 'Bulgaria'),
	('RO', 'Romania', 'HU', 'Hungary'),
	('RO', 'Romania', 'MD', 'Moldova (the Republic of)'),
	('RO', 'Romania', 'RS', 'Serbia'),
	('RO', 'Romania', 'UA', 'Ukraine'),
	('RS', 'Serbia', 'AL', 'Albania'),
	('RS', 'Serbia', 'BA', 'Bosnia and Herzegovina'),
	('RS', 'Serbia', 'BG', 'Bulgaria'),
	('RS', 'Serbia', 'HR', 'Croatia'),
	('RS', 'Serbia', 'HU', 'Hungary'),
	('RS', 'Serbia', 'ME', 'Montenegro'),
	('RS', 'Serbia', 'MK', 'North Macedonia'),
	('RS', 'Serbia', 'RO', 'Romania'),
	('RU', 'Russian Federation', 'AZ', 'Azerbaijan'),
	('RU', 'Russian Federation', 'BY', 'Belarus'),
	('RU', 'Russian Federation', 'CN', 'China'),
	('RU', 'Russian Federation', 'EE', 'Estonia'),
	('RU', 'Russian Federation', 'FI', 'Finland'),
	('RU', 'Russian Federation', 'GE', 'Georgia'),
	('RU', 'Russian Federation', 'KZ', 'Kazakhstan'),
	('RU', 'Russian Federation', 'KP', 'Korea (Democratic People\'s Republic of)'),
	('RU', 'Russian Federation', 'LV', 'Latvia'),
	('RU', 'Russian Federation', 'LT', 'Lithuania'),
	('RU', 'Russian Federation', 'MN', 'Mongolia'),
	('RU', 'Russian Federation', 'NO', 'Norway'),
	('RU', 'Russian Federation', 'PL', 'Poland'),
	('RU', 'Russian Federation', 'UA', 'Ukraine'),
	('RW', 'Rwanda', 'BI', 'Burundi'),
	('RW', 'Rwanda', 'CD', 'Congo (the Democratic Republic of the)'),
	('RW', 'Rwanda', 'TZ', 'Tanzania (the United Republic of)'),
	('RW', 'Rwanda', 'UG', 'Uganda'),
	('SA', 'Saudi Arabia', 'IQ', 'Iraq'),
	('SA', 'Saudi Arabia', 'JO', 'Jordan'),
	('SA', 'Saudi Arabia', 'KW', 'Kuwait'),
	('SA', 'Saudi Arabia', 'OM', 'Oman'),
	('SA', 'Saudi Arabia', 'QA', 'Qatar'),
	('SA', 'Saudi Arabia', 'AE', 'United Arab Emirates'),
	('SA', 'Saudi Arabia', 'YE', 'Yemen'),
	('SB', 'Solomon Islands', '', ''),
	('SC', 'Seychelles', '', ''),
	('SD', 'Sudan', 'CF', 'Central African Republic'),
	('SD', 'Sudan', 'TD', 'Chad'),
	('SD', 'Sudan', 'EG', 'Egypt'),
	('SD', 'Sudan', 'ET', 'Ethiopia'),
	('SD', 'Sudan', 'ER', 'Eritrea'),
	('SD', 'Sudan', 'LY', 'Libya'),
	('SD', 'Sudan', 'SS', 'South Sudan'),
	('SE', 'Sweden', 'FI', 'Finland'),
	('SE', 'Sweden', 'NO', 'Norway'),
	('SG', 'Singapore', '', ''),
	('SH', 'Saint Helena,"Ascension and Tristan da Cunha', '', ''),
	('SI', 'Slovenia', 'AT', 'Austria'),
	('SI', 'Slovenia', 'HR', 'Croatia'),
	('SI', 'Slovenia', 'HU', 'Hungary'),
	('SI', 'Slovenia', 'IT', 'Italy'),
	('SJ', 'Svalbard and Jan Mayen', '', ''),
	('SK', 'Slovakia', 'AT', 'Austria'),
	('SK', 'Slovakia', 'CZ', 'Czechia'),
	('SK', 'Slovakia', 'HU', 'Hungary'),
	('SK', 'Slovakia', 'PL', 'Poland'),
	('SK', 'Slovakia', 'UA', 'Ukraine'),
	('SL', 'Sierra Leone', 'GN', 'Guinea'),
	('SL', 'Sierra Leone', 'LR', 'Liberia'),
	('SM', 'San Marino', 'IT', 'Italy'),
	('SN', 'Senegal', 'GM', 'Gambia (the)'),
	('SN', 'Senegal', 'GN', 'Guinea'),
	('SN', 'Senegal', 'GW', 'Guinea-Bissau'),
	('SN', 'Senegal', 'ML', 'Mali'),
	('SN', 'Senegal', 'MR', 'Mauritania'),
	('SO', 'Somalia', 'DJ', 'Djibouti'),
	('SO', 'Somalia', 'ET', 'Ethiopia'),
	('SO', 'Somalia', 'KE', 'Kenya'),
	('SR', 'Suriname', 'BR', 'Brazil'),
	('SR', 'Suriname', 'GF', 'French Guiana'),
	('SR', 'Suriname', 'GY', 'Guyana'),
	('SS', 'South Sudan', 'CF', 'Central African Republic'),
	('SS', 'South Sudan', 'CD', 'Congo (the Democratic Republic of the)'),
	('SS', 'South Sudan', 'ET', 'Ethiopia'),
	('SS', 'South Sudan', 'KE', 'Kenya'),
	('SS', 'South Sudan', 'SD', 'Sudan'),
	('SS', 'South Sudan', 'UG', 'Uganda'),
	('ST', 'Sao Tome and Principe', '', ''),
	('SV', 'El Salvador', 'GT', 'Guatemala'),
	('SV', 'El Salvador', 'HN', 'Honduras'),
	('SX', 'Sint Maarten (Dutch part)', 'MF', 'Saint Martin (French part)'),
	('SY', 'Syrian Arab Republic', 'IQ', 'Iraq'),
	('SY', 'Syrian Arab Republic', 'IL', 'Israel'),
	('SY', 'Syrian Arab Republic', 'JO', 'Jordan'),
	('SY', 'Syrian Arab Republic', 'LB', 'Lebanon'),
	('SY', 'Syrian Arab Republic', 'TR', 'Turkey'),
	('SZ', 'Eswatini', 'MZ', 'Mozambique'),
	('SZ', 'Eswatini', 'ZA', 'South Africa'),
	('TC', 'Turks and Caicos Islands', '', ''),
	('TD', 'Chad', 'CM', 'Cameroon'),
	('TD', 'Chad', 'CF', 'Central African Republic'),
	('TD', 'Chad', 'LY', 'Libya'),
	('TD', 'Chad', 'NE', 'Niger'),
	('TD', 'Chad', 'NG', 'Nigeria'),
	('TD', 'Chad', 'SD', 'Sudan'),
	('TF', 'French Southern Territories', '', ''),
	('TG', 'Togo', 'BJ', 'Benin'),
	('TG', 'Togo', 'BF', 'Burkina Faso'),
	('TG', 'Togo', 'GH', 'Ghana'),
	('TH', 'Thailand', 'KH', 'Cambodia'),
	('TH', 'Thailand', 'LA', 'Lao People\'s Democratic Republic'),
	('TH', 'Thailand', 'MY', 'Malaysia'),
	('TH', 'Thailand', 'MM', 'Myanmar'),
	('TJ', 'Tajikistan', 'AF', 'Afghanistan'),
	('TJ', 'Tajikistan', 'CN', 'China'),
	('TJ', 'Tajikistan', 'KG', 'Kyrgyzstan'),
	('TJ', 'Tajikistan', 'UZ', 'Uzbekistan'),
	('TK', 'Tokelau', '', ''),
	('TL', 'Timor-Leste', 'ID', 'Indonesia'),
	('TM', 'Turkmenistan', 'AF', 'Afghanistan'),
	('TM', 'Turkmenistan', 'IR', 'Iran (Islamic Republic of)'),
	('TM', 'Turkmenistan', 'KZ', 'Kazakhstan'),
	('TM', 'Turkmenistan', 'UZ', 'Uzbekistan'),
	('TN', 'Tunisia', 'DZ', 'Algeria'),
	('TN', 'Tunisia', 'LY', 'Libya'),
	('TO', 'Tonga', '', ''),
	('TR', 'Turkey', 'AM', 'Armenia'),
	('TR', 'Turkey', 'AZ', 'Azerbaijan'),
	('TR', 'Turkey', 'BG', 'Bulgaria'),
	('TR', 'Turkey', 'GE', 'Georgia'),
	('TR', 'Turkey', 'GR', 'Greece'),
	('TR', 'Turkey', 'IR', 'Iran (Islamic Republic of)'),
	('TR', 'Turkey', 'IQ', 'Iraq'),
	('TR', 'Turkey', 'SY', 'Syrian Arab Republic'),
	('TT', 'Trinidad and Tobago', '', ''),
	('TV', 'Tuvalu', '', ''),
	('TW', 'Taiwan (Province of China)', '', ''),
	('TZ', 'Tanzania (the United Republic of)', 'BI', 'Burundi'),
	('TZ', 'Tanzania (the United Republic of)', 'CD', 'Congo (the Democratic Republic of the)'),
	('TZ', 'Tanzania (the United Republic of)', 'KE', 'Kenya'),
	('TZ', 'Tanzania (the United Republic of)', 'MW', 'Malawi'),
	('TZ', 'Tanzania (the United Republic of)', 'MZ', 'Mozambique'),
	('TZ', 'Tanzania (the United Republic of)', 'RW', 'Rwanda'),
	('TZ', 'Tanzania (the United Republic of)', 'UG', 'Uganda'),
	('TZ', 'Tanzania (the United Republic of)', 'ZM', 'Zambia'),
	('UA', 'Ukraine', 'BY', 'Belarus'),
	('UA', 'Ukraine', 'HU', 'Hungary'),
	('UA', 'Ukraine', 'MD', 'Moldova (the Republic of)'),
	('UA', 'Ukraine', 'PL', 'Poland'),
	('UA', 'Ukraine', 'RO', 'Romania'),
	('UA', 'Ukraine', 'RU', 'Russian Federation'),
	('UA', 'Ukraine', 'SK', 'Slovakia'),
	('UG', 'Uganda', 'CD', 'Congo (the Democratic Republic of the)'),
	('UG', 'Uganda', 'KE', 'Kenya'),
	('UG', 'Uganda', 'RW', 'Rwanda'),
	('UG', 'Uganda', 'SS', 'South Sudan'),
	('UG', 'Uganda', 'TZ', 'Tanzania (the United Republic of)'),
	('UM', 'United States Minor Outlying Islands', '', ''),
	('US', 'United States of America', 'CA', 'Canada'),
	('US', 'United States of America', 'MX', 'Mexico'),
	('UY', 'Uruguay', 'AR', 'Argentina'),
	('UY', 'Uruguay', 'BR', 'Brazil'),
	('UZ', 'Uzbekistan', 'AF', 'Afghanistan'),
	('UZ', 'Uzbekistan', 'KZ', 'Kazakhstan'),
	('UZ', 'Uzbekistan', 'KG', 'Kyrgyzstan'),
	('UZ', 'Uzbekistan', 'TJ', 'Tajikistan'),
	('UZ', 'Uzbekistan', 'TM', 'Turkmenistan'),
	('VA', 'Holy See', 'IT', 'Italy'),
	('VC', 'Saint Vincent and the Grenadines', '', ''),
	('VE', 'Venezuela (Bolivarian Republic of)', 'BR', 'Brazil'),
	('VE', 'Venezuela (Bolivarian Republic of)', 'CO', 'Colombia'),
	('VE', 'Venezuela (Bolivarian Republic of)', 'GY', 'Guyana'),
	('VG', 'Virgin Islands (British)', '', ''),
	('VI', 'Virgin Islands (U.S.)', '', ''),
	('VN', 'Viet Nam', 'KH', 'Cambodia'),
	('VN', 'Viet Nam', 'CN', 'China'),
	('VN', 'Viet Nam', 'LA', 'Lao People\'s Democratic Republic'),
	('VU', 'Vanuatu', '', ''),
	('WF', 'Wallis and Futuna', '', ''),
	('WS', 'Samoa', '', ''),
	('YE', 'Yemen', 'OM', 'Oman'),
	('YE', 'Yemen', 'SA', 'Saudi Arabia'),
	('YT', 'Mayotte', '', ''),
	('ZA', 'South Africa', 'BW', 'Botswana'),
	('ZA', 'South Africa', 'LS', 'Lesotho'),
	('ZA', 'South Africa', 'MZ', 'Mozambique'),
	('ZA', 'South Africa', 'NA', 'Namibia'),
	('ZA', 'South Africa', 'SZ', 'Eswatini'),
	('ZA', 'South Africa', 'ZW', 'Zimbabwe'),
	('ZM', 'Zambia', 'AO', 'Angola'),
	('ZM', 'Zambia', 'BW', 'Botswana'),
	('ZM', 'Zambia', 'CD', 'Congo (the Democratic Republic of the)'),
	('ZM', 'Zambia', 'MW', 'Malawi'),
	('ZM', 'Zambia', 'MZ', 'Mozambique'),
	('ZM', 'Zambia', 'NA', 'Namibia'),
	('ZM', 'Zambia', 'TZ', 'Tanzania (the United Republic of)'),
	('ZM', 'Zambia', 'ZW', 'Zimbabwe'),
	('ZW', 'Zimbabwe', 'BW', 'Botswana'),
	('ZW', 'Zimbabwe', 'MZ', 'Mozambique'),
	('ZW', 'Zimbabwe', 'ZA', 'South Africa'),
	('ZW', 'Zimbabwe', 'ZM', 'Zambia');
/*!40000 ALTER TABLE `country_borders` ENABLE KEYS */;

-- Dumping structure for table migrazioni.country_population
CREATE TABLE IF NOT EXISTS `country_population` (
  `Country` varchar(100) COLLATE utf8mb3_bin NOT NULL,
  `Region` varchar(100) COLLATE utf8mb3_bin DEFAULT NULL,
  `Population` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`Country`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_bin;

-- Dumping data for table migrazioni.country_population: ~227 rows (approximately)
/*!40000 ALTER TABLE `country_population` DISABLE KEYS */;
INSERT INTO `country_population` (`Country`, `Region`, `Population`) VALUES
	('Afghanistan ', 'ASIA (EX. NEAR EAST)         ', 31056997),
	('Albania ', 'EASTERN EUROPE                     ', 3581655),
	('Algeria ', 'NORTHERN AFRICA                    ', 32930091),
	('American Samoa ', 'OCEANIA                            ', 57794),
	('Andorra ', 'WESTERN EUROPE                     ', 71201),
	('Angola ', 'SUB-SAHARAN AFRICA                 ', 12127071),
	('Anguilla ', 'LATIN AMER. & CARIB    ', 13477),
	('Antigua & Barbuda ', 'LATIN AMER. & CARIB    ', 69108),
	('Argentina ', 'LATIN AMER. & CARIB    ', 39921833),
	('Armenia ', 'C.W. OF IND. STATES ', 2976372),
	('Aruba ', 'LATIN AMER. & CARIB    ', 71891),
	('Australia ', 'OCEANIA                            ', 20264082),
	('Austria ', 'WESTERN EUROPE                     ', 8192880),
	('Azerbaijan ', 'C.W. OF IND. STATES ', 7961619),
	('Bahamas, The ', 'LATIN AMER. & CARIB    ', 303770),
	('Bahrain ', 'NEAR EAST                          ', 698585),
	('Bangladesh ', 'ASIA (EX. NEAR EAST)         ', 147365352),
	('Barbados ', 'LATIN AMER. & CARIB    ', 279912),
	('Belarus ', 'C.W. OF IND. STATES ', 10293011),
	('Belgium ', 'WESTERN EUROPE                     ', 10379067),
	('Belize ', 'LATIN AMER. & CARIB    ', 287730),
	('Benin ', 'SUB-SAHARAN AFRICA                 ', 7862944),
	('Bermuda ', 'NORTHERN AMERICA                   ', 65773),
	('Bhutan ', 'ASIA (EX. NEAR EAST)         ', 2279723),
	('Bolivia ', 'LATIN AMER. & CARIB    ', 8989046),
	('Bosnia & Herzegovina ', 'EASTERN EUROPE                     ', 4498976),
	('Botswana ', 'SUB-SAHARAN AFRICA                 ', 1639833),
	('Brazil ', 'LATIN AMER. & CARIB    ', 188078227),
	('British Virgin Is. ', 'LATIN AMER. & CARIB    ', 23098),
	('Brunei ', 'ASIA (EX. NEAR EAST)         ', 379444),
	('Bulgaria ', 'EASTERN EUROPE                     ', 7385367),
	('Burkina Faso ', 'SUB-SAHARAN AFRICA                 ', 13902972),
	('Burma ', 'ASIA (EX. NEAR EAST)         ', 47382633),
	('Burundi ', 'SUB-SAHARAN AFRICA                 ', 8090068),
	('Cambodia ', 'ASIA (EX. NEAR EAST)         ', 13881427),
	('Cameroon ', 'SUB-SAHARAN AFRICA                 ', 17340702),
	('Canada ', 'NORTHERN AMERICA                   ', 33098932),
	('Cape Verde ', 'SUB-SAHARAN AFRICA                 ', 420979),
	('Cayman Islands ', 'LATIN AMER. & CARIB    ', 45436),
	('Central African Rep. ', 'SUB-SAHARAN AFRICA                 ', 4303356),
	('Chad ', 'SUB-SAHARAN AFRICA                 ', 9944201),
	('Chile ', 'LATIN AMER. & CARIB    ', 16134219),
	('China ', 'ASIA (EX. NEAR EAST)         ', 1313973713),
	('Colombia ', 'LATIN AMER. & CARIB    ', 43593035),
	('Comoros ', 'SUB-SAHARAN AFRICA                 ', 690948),
	('Congo, Dem. Rep. ', 'SUB-SAHARAN AFRICA                 ', 62660551),
	('Congo, Repub. of the ', 'SUB-SAHARAN AFRICA                 ', 3702314),
	('Cook Islands ', 'OCEANIA                            ', 21388),
	('Costa Rica ', 'LATIN AMER. & CARIB    ', 4075261),
	('Cote d\'Ivoire ', 'SUB-SAHARAN AFRICA                 ', 17654843),
	('Croatia ', 'EASTERN EUROPE                     ', 4494749),
	('Cuba ', 'LATIN AMER. & CARIB    ', 11382820),
	('Cyprus ', 'NEAR EAST                          ', 784301),
	('Czech Republic ', 'EASTERN EUROPE                     ', 10235455),
	('Denmark ', 'WESTERN EUROPE                     ', 5450661),
	('Djibouti ', 'SUB-SAHARAN AFRICA                 ', 486530),
	('Dominica ', 'LATIN AMER. & CARIB    ', 68910),
	('Dominican Republic ', 'LATIN AMER. & CARIB    ', 9183984),
	('East Timor ', 'ASIA (EX. NEAR EAST)         ', 1062777),
	('Ecuador ', 'LATIN AMER. & CARIB    ', 13547510),
	('Egypt ', 'NORTHERN AFRICA                    ', 78887007),
	('El Salvador ', 'LATIN AMER. & CARIB    ', 6822378),
	('Equatorial Guinea ', 'SUB-SAHARAN AFRICA                 ', 540109),
	('Eritrea ', 'SUB-SAHARAN AFRICA                 ', 4786994),
	('Estonia ', 'BALTICS                            ', 1324333),
	('Ethiopia ', 'SUB-SAHARAN AFRICA                 ', 74777981),
	('Faroe Islands ', 'WESTERN EUROPE                     ', 47246),
	('Fiji ', 'OCEANIA                            ', 905949),
	('Finland ', 'WESTERN EUROPE                     ', 5231372),
	('France ', 'WESTERN EUROPE                     ', 60876136),
	('French Guiana ', 'LATIN AMER. & CARIB    ', 199509),
	('French Polynesia ', 'OCEANIA                            ', 274578),
	('Gabon ', 'SUB-SAHARAN AFRICA                 ', 1424906),
	('Gambia, The ', 'SUB-SAHARAN AFRICA                 ', 1641564),
	('Gaza Strip ', 'NEAR EAST                          ', 1428757),
	('Georgia ', 'C.W. OF IND. STATES ', 4661473),
	('Germany ', 'WESTERN EUROPE                     ', 82422299),
	('Ghana ', 'SUB-SAHARAN AFRICA                 ', 22409572),
	('Gibraltar ', 'WESTERN EUROPE                     ', 27928),
	('Greece ', 'WESTERN EUROPE                     ', 10688058),
	('Greenland ', 'NORTHERN AMERICA                   ', 56361),
	('Grenada ', 'LATIN AMER. & CARIB    ', 89703),
	('Guadeloupe ', 'LATIN AMER. & CARIB    ', 452776),
	('Guam ', 'OCEANIA                            ', 171019),
	('Guatemala ', 'LATIN AMER. & CARIB    ', 12293545),
	('Guernsey ', 'WESTERN EUROPE                     ', 65409),
	('Guinea ', 'SUB-SAHARAN AFRICA                 ', 9690222),
	('Guinea-Bissau ', 'SUB-SAHARAN AFRICA                 ', 1442029),
	('Guyana ', 'LATIN AMER. & CARIB    ', 767245),
	('Haiti ', 'LATIN AMER. & CARIB    ', 8308504),
	('Honduras ', 'LATIN AMER. & CARIB    ', 7326496),
	('Hong Kong ', 'ASIA (EX. NEAR EAST)         ', 6940432),
	('Hungary ', 'EASTERN EUROPE                     ', 9981334),
	('Iceland ', 'WESTERN EUROPE                     ', 299388),
	('India ', 'ASIA (EX. NEAR EAST)         ', 1095351995),
	('Indonesia ', 'ASIA (EX. NEAR EAST)         ', 245452739),
	('Iran ', 'ASIA (EX. NEAR EAST)         ', 68688433),
	('Iraq ', 'NEAR EAST                          ', 26783383),
	('Ireland ', 'WESTERN EUROPE                     ', 4062235),
	('Isle of Man ', 'WESTERN EUROPE                     ', 75441),
	('Israel ', 'NEAR EAST                          ', 6352117),
	('Italy ', 'WESTERN EUROPE                     ', 58133509),
	('Jamaica ', 'LATIN AMER. & CARIB    ', 2758124),
	('Japan ', 'ASIA (EX. NEAR EAST)         ', 127463611),
	('Jersey ', 'WESTERN EUROPE                     ', 91084),
	('Jordan ', 'NEAR EAST                          ', 5906760),
	('Kazakhstan ', 'C.W. OF IND. STATES ', 15233244),
	('Kenya ', 'SUB-SAHARAN AFRICA                 ', 34707817),
	('Kiribati ', 'OCEANIA                            ', 105432),
	('Korea, North ', 'ASIA (EX. NEAR EAST)         ', 23113019),
	('Korea, South ', 'ASIA (EX. NEAR EAST)         ', 48846823),
	('Kuwait ', 'NEAR EAST                          ', 2418393),
	('Kyrgyzstan ', 'C.W. OF IND. STATES ', 5213898),
	('Laos ', 'ASIA (EX. NEAR EAST)         ', 6368481),
	('Latvia ', 'BALTICS                            ', 2274735),
	('Lebanon ', 'NEAR EAST                          ', 3874050),
	('Lesotho ', 'SUB-SAHARAN AFRICA                 ', 2022331),
	('Liberia ', 'SUB-SAHARAN AFRICA                 ', 3042004),
	('Libya ', 'NORTHERN AFRICA                    ', 5900754),
	('Liechtenstein ', 'WESTERN EUROPE                     ', 33987),
	('Lithuania ', 'BALTICS                            ', 3585906),
	('Luxembourg ', 'WESTERN EUROPE                     ', 474413),
	('Macau ', 'ASIA (EX. NEAR EAST)         ', 453125),
	('Macedonia ', 'EASTERN EUROPE                     ', 2050554),
	('Madagascar ', 'SUB-SAHARAN AFRICA                 ', 18595469),
	('Malawi ', 'SUB-SAHARAN AFRICA                 ', 13013926),
	('Malaysia ', 'ASIA (EX. NEAR EAST)         ', 24385858),
	('Maldives ', 'ASIA (EX. NEAR EAST)         ', 359008),
	('Mali ', 'SUB-SAHARAN AFRICA                 ', 11716829),
	('Malta ', 'WESTERN EUROPE                     ', 400214),
	('Marshall Islands ', 'OCEANIA                            ', 60422),
	('Martinique ', 'LATIN AMER. & CARIB    ', 436131),
	('Mauritania ', 'SUB-SAHARAN AFRICA                 ', 3177388),
	('Mauritius ', 'SUB-SAHARAN AFRICA                 ', 1240827),
	('Mayotte ', 'SUB-SAHARAN AFRICA                 ', 201234),
	('Mexico ', 'LATIN AMER. & CARIB    ', 107449525),
	('Micronesia, Fed. St. ', 'OCEANIA                            ', 108004),
	('Moldova ', 'C.W. OF IND. STATES ', 4466706),
	('Monaco ', 'WESTERN EUROPE                     ', 32543),
	('Mongolia ', 'ASIA (EX. NEAR EAST)         ', 2832224),
	('Montserrat ', 'LATIN AMER. & CARIB    ', 9439),
	('Morocco ', 'NORTHERN AFRICA                    ', 33241259),
	('Mozambique ', 'SUB-SAHARAN AFRICA                 ', 19686505),
	('N. Mariana Islands ', 'OCEANIA                            ', 82459),
	('Namibia ', 'SUB-SAHARAN AFRICA                 ', 2044147),
	('Nauru ', 'OCEANIA                            ', 13287),
	('Nepal ', 'ASIA (EX. NEAR EAST)         ', 28287147),
	('Netherlands ', 'WESTERN EUROPE                     ', 16491461),
	('Netherlands Antilles ', 'LATIN AMER. & CARIB    ', 221736),
	('New Caledonia ', 'OCEANIA                            ', 219246),
	('New Zealand ', 'OCEANIA                            ', 4076140),
	('Nicaragua ', 'LATIN AMER. & CARIB    ', 5570129),
	('Niger ', 'SUB-SAHARAN AFRICA                 ', 12525094),
	('Nigeria ', 'SUB-SAHARAN AFRICA                 ', 131859731),
	('Norway ', 'WESTERN EUROPE                     ', 4610820),
	('Oman ', 'NEAR EAST                          ', 3102229),
	('Pakistan ', 'ASIA (EX. NEAR EAST)         ', 165803560),
	('Palau ', 'OCEANIA                            ', 20579),
	('Panama ', 'LATIN AMER. & CARIB    ', 3191319),
	('Papua New Guinea ', 'OCEANIA                            ', 5670544),
	('Paraguay ', 'LATIN AMER. & CARIB    ', 6506464),
	('Peru ', 'LATIN AMER. & CARIB    ', 28302603),
	('Philippines ', 'ASIA (EX. NEAR EAST)         ', 89468677),
	('Poland ', 'EASTERN EUROPE                     ', 38536869),
	('Portugal ', 'WESTERN EUROPE                     ', 10605870),
	('Puerto Rico ', 'LATIN AMER. & CARIB    ', 3927188),
	('Qatar ', 'NEAR EAST                          ', 885359),
	('Reunion ', 'SUB-SAHARAN AFRICA                 ', 787584),
	('Romania ', 'EASTERN EUROPE                     ', 22303552),
	('Russia ', 'C.W. OF IND. STATES ', 142893540),
	('Rwanda ', 'SUB-SAHARAN AFRICA                 ', 8648248),
	('Saint Helena ', 'SUB-SAHARAN AFRICA                 ', 7502),
	('Saint Kitts & Nevis ', 'LATIN AMER. & CARIB    ', 39129),
	('Saint Lucia ', 'LATIN AMER. & CARIB    ', 168458),
	('Saint Vincent and the Grenadines ', 'LATIN AMER. & CARIB    ', 117848),
	('Samoa ', 'OCEANIA                            ', 176908),
	('San Marino ', 'WESTERN EUROPE                     ', 29251),
	('Sao Tome & Principe ', 'SUB-SAHARAN AFRICA                 ', 193413),
	('Saudi Arabia ', 'NEAR EAST                          ', 27019731),
	('Senegal ', 'SUB-SAHARAN AFRICA                 ', 11987121),
	('Serbia ', 'EASTERN EUROPE                     ', 9396411),
	('Seychelles ', 'SUB-SAHARAN AFRICA                 ', 81541),
	('Sierra Leone ', 'SUB-SAHARAN AFRICA                 ', 6005250),
	('Singapore ', 'ASIA (EX. NEAR EAST)         ', 4492150),
	('Slovakia ', 'EASTERN EUROPE                     ', 5439448),
	('Slovenia ', 'EASTERN EUROPE                     ', 2010347),
	('Solomon Islands ', 'OCEANIA                            ', 552438),
	('Somalia ', 'SUB-SAHARAN AFRICA                 ', 8863338),
	('South Africa ', 'SUB-SAHARAN AFRICA                 ', 44187637),
	('Spain ', 'WESTERN EUROPE                     ', 40397842),
	('Sri Lanka ', 'ASIA (EX. NEAR EAST)         ', 20222240),
	('St Pierre & Miquelon ', 'NORTHERN AMERICA                   ', 7026),
	('Sudan ', 'SUB-SAHARAN AFRICA                 ', 41236378),
	('Suriname ', 'LATIN AMER. & CARIB    ', 439117),
	('Swaziland ', 'SUB-SAHARAN AFRICA                 ', 1136334),
	('Sweden ', 'WESTERN EUROPE                     ', 9016596),
	('Switzerland ', 'WESTERN EUROPE                     ', 7523934),
	('Syria ', 'NEAR EAST                          ', 18881361),
	('Taiwan ', 'ASIA (EX. NEAR EAST)         ', 23036087),
	('Tajikistan ', 'C.W. OF IND. STATES ', 7320815),
	('Tanzania ', 'SUB-SAHARAN AFRICA                 ', 37445392),
	('Thailand ', 'ASIA (EX. NEAR EAST)         ', 64631595),
	('Togo ', 'SUB-SAHARAN AFRICA                 ', 5548702),
	('Tonga ', 'OCEANIA                            ', 114689),
	('Trinidad & Tobago ', 'LATIN AMER. & CARIB    ', 1065842),
	('Tunisia ', 'NORTHERN AFRICA                    ', 10175014),
	('Turkey ', 'NEAR EAST                          ', 70413958),
	('Turkmenistan ', 'C.W. OF IND. STATES ', 5042920),
	('Turks & Caicos Is ', 'LATIN AMER. & CARIB    ', 21152),
	('Tuvalu ', 'OCEANIA                            ', 11810),
	('Uganda ', 'SUB-SAHARAN AFRICA                 ', 28195754),
	('Ukraine ', 'C.W. OF IND. STATES ', 46710816),
	('United Arab Emirates ', 'NEAR EAST                          ', 2602713),
	('United Kingdom ', 'WESTERN EUROPE                     ', 60609153),
	('United States ', 'NORTHERN AMERICA                   ', 298444215),
	('Uruguay ', 'LATIN AMER. & CARIB    ', 3431932),
	('Uzbekistan ', 'C.W. OF IND. STATES ', 27307134),
	('Vanuatu ', 'OCEANIA                            ', 208869),
	('Venezuela ', 'LATIN AMER. & CARIB    ', 25730435),
	('Vietnam ', 'ASIA (EX. NEAR EAST)         ', 84402966),
	('Virgin Islands ', 'LATIN AMER. & CARIB    ', 108605),
	('Wallis and Futuna ', 'OCEANIA                            ', 16025),
	('West Bank ', 'NEAR EAST                          ', 2460492),
	('Western Sahara ', 'NORTHERN AFRICA                    ', 273008),
	('Yemen ', 'NEAR EAST                          ', 21456188),
	('Zambia ', 'SUB-SAHARAN AFRICA                 ', 11502010),
	('Zimbabwe ', 'SUB-SAHARAN AFRICA                 ', 12236805);
/*!40000 ALTER TABLE `country_population` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
